on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Type example test

jobs:
    test:
      name: Run JS and D
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]
          dc: [dmd-latest, ldc-latest]
          node-version: [12.x]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install D compiler
          uses: dlang-community/setup-dlang@v1
          with:
            compiler: ${{ matrix.dc }}
        - name: Run tests
          run: dub run :type_examples
          env:
            CI: true
